// src/lib/redirects.js
// Old slug -> New slug ka map, aur Alias map (URL same rahe, content dusre slug ka aaye)

// 🔁 FULL REDIRECT: match hone par URL bhi badal jayegi (address bar update hoga)
const REDIRECTS = {
  // ---- Course redirects ----
  "fetal-medicine-fellowship": "fellowship-in-fetal-medicine",
  "fellowship-in-obstetrics-gynaecology": "fellowship-in-obstetrics-and-gynaecology",
  "fellowship-in-head-and-neck-surgicl-oncology": "fellowship-in-head-neck-surgery",
  "fellowship-in-anorectal-plus-laser-proctology": "fellowship-in-anorectal-and-laser-proctology",
  "fellowship-in-aesthetic-dentistry": "fellowship-in-aesthetic-dentistry-surgery",
  "certificate-in-infection-and-prevention-control": "certificate-in-infection-control-and-prevention",
  "fellowship-in-orthodontics": "fellowship-in-pediatric-orthodontics",
  "fellowship-in-laparoscopy": "fellowship-in-laparoscopic-surgery",
  "certificate-in-histopathology": "fellowship-in-histopathology",
  "fellowship-in-pediatric-dermatology": "fellowship-in-pediatrics-dermatology",
  "fellowship-in-pediatric-neonatology": "fellowship-in-pediatrics-neonatology",
  "fellowship-in-oral-and-maxillofacial-radiology": "fellowship-in-oral-radiology",
  "fellowship-in-maxillofacial-radiology": "fellowship-in-oral-radiology",

  "fellowship-in-gynaecologic-oncology": "fellowship-in-robotic-gynaecological-oncology",
  "fellowship-in-arthroscopy-sports-medicine": "fellowship-in-arthroscopy-and-sports-medicine",
  "fellowship-in-head-and-neck-surgical-oncology": "fellowship-in-head-and-neck-oncosurgery",
  "fellowship-in-pulmonary-medicine": "fellowship-in-pulmonology-medicine",
  "fellowship-in-orthopedics": "fellowship-in-orthopedic",
  "fellowship-in-pediatrics-neurology": "fellowship-in-pediatric-neurology",
  "fellowship-in-emergency-medicine": "certificate-in-emergency-medicine",
  "certificate-in-critical-care": "fellowship-in-critical-care",
  "fellowship-in-pediatric-ophthalmology": "fellowship-in-pediatric-ophthalmology-strabismus",
  "fellowship-in-pediatrics-endocrinology": "fellowship-in-endocrinology",
  "fellowship-in-pulmonology": "fellowship-in-pulmonology-medicine",
  "certificate-in-diabetic-footcare": "certificate-in-diabetic-foot-care",
  "fellowship-in-anesthesiology": "fellowship-in-anesthesia",
  "fellowship-in-clinical-nutrition": "certificate-in-clinical-nutrition-and-dietetics",
  "fellowship-in-laparoscopy-hysteroscopy": "fellowship-in-laparoscopy-and-hysteroscopy",
  "certificate-in-obstetrics-gynaecology": "certificate-in-obstetrics-and-gynaecology",
  "fellowship-in-neonatal-surgery": "fellowship-in-neonatology",
  "certificate-in-nutrition-and-dietetics": "certificate-in-clinical-nutrition-and-dietetics",
  "fellowship-in-pediatric-genetics-and-metabolic": "fellowship-in-pediatric-genetics-and-metabolism",
  "fellowship-in-orthopaedic": "fellowship-in-orthopedic",
  "fellowship-in-gastrology": "fellowship-in-gastroenterology",

  // ---- Blog redirects: root (/slug) -> /blog/slug ----
  "types-of-genetic-testing": "blog/types-of-genetic-testing",
  "congenital-heart-disease": "blog/congenital-heart-disease",
  "cancer-screening-guidelines-india": "blog/cancer-screening-guidelines-india",
  "how-to-become-an-orthopedic-surgeon-after-mbbs": "blog/how-to-become-an-orthopedic-surgeon-after-mbbs",
  "medical-writing-career-after-mbbs": "blog/medical-writing-career-after-mbbs",
  "clinical-research-pharma-careers-after-mbbs": "blog/clinical-research-pharma-careers-after-mbbs",
  "hospital-administration-career-after-mbbs": "blog/hospital-administration-career-after-mbbs",
  "precision-oncology-fellowship": "blog/precision-oncology-fellowship",
  "dermatologist-salary-in-india": "blog/dermatologist-salary-in-india",
  "cosmetic-vs-clinical-dermatology-career": "blog/cosmetic-vs-clinical-dermatology-career",
  "medical-vs-surgical-vs-radiation-oncology-fellowship": "blog/medical-vs-surgical-vs-radiation-oncology-fellowship",
  "fellowship-in-oncology-vs-dm-medical-oncology": "blog/fellowship-in-oncology-vs-dm-medical-oncology",
  "easiest-medical-specialization-to-get-india": "blog/easiest-medical-specialization-to-get-india",
  "dermoscopy-for-general-physicians": "blog/dermoscopy-for-general-physicians",
  "heart-failure-and-cardiomyopathies": "blog/heart-failure-and-cardiomyopathies",
  "dermoscopy-training-general-physicians": "blog/dermoscopy-training-general-physicians",
  "doctor-specialization-salary-comparison": "blog/doctor-specialization-salary-comparison",
  "medical-vs-surgical-specialization": "blog/medical-vs-surgical-specialization",
  "pediatric-skin-conditions-physician-guide": "blog/pediatric-skin-conditions-physician-guide",
  "future-scope-medical-specialization-india": "blog/future-scope-medical-specialization-india",
  "rmo-vs-duty-doctor-vs-junior-resident": "blog/rmo-vs-duty-doctor-vs-junior-resident",
  "trichology-vs-dermatology-hair-loss-india": "blog/trichology-vs-dermatology-hair-loss-india",
  "medical-officer-vs-junior-resident-after-mbbs": "blog/medical-officer-vs-junior-resident-after-mbbs",
  "pigmentation-disorders-indian-skin": "blog/pigmentation-disorders-indian-skin",
  "medical-specialization-work-life-balance": "blog/medical-specialization-work-life-balance",
  "md-vs-ms-vs-dnb-complete-guide": "blog/md-vs-ms-vs-dnb-complete-guide",
  "eczema-vs-psoriasis-vs-fungal-rash-diagnosis-2": "blog/eczema-vs-psoriasis-vs-fungal-rash-diagnosis-2",
  "steroid-modified-tinea-india": "blog/steroid-modified-tinea-india",
  "cpd-accreditation-for-doctors-india": "blog/cpd-accreditation-for-doctors-india",
  "recurrent-fungal-infection-treatment-india": "blog/recurrent-fungal-infection-treatment-india",
  "acne-management-general-physicians-india": "blog/acne-management-general-physicians-india",
  "best-specialization-for-female-doctors": "blog/best-specialization-for-female-doctors",
  "infertility-evaluation-structured-workup-general-practice": "blog/infertility-evaluation-structured-workup-general-practice",
  "fellowship-in-infertility-management-curriculum-eligibility": "blog/fellowship-in-infertility-management-curriculum-eligibility",
  "first-trimester-screening-timing-protocol-counselling": "blog/first-trimester-screening-timing-protocol-counselling",
  "fetal-medicine-fellowship-curriculum-eligibility-competencies": "blog/fetal-medicine-fellowship-curriculum-eligibility-competencies",
  "ecg-interpretation-mistakes-systematic-reading": "blog/ecg-interpretation-mistakes-systematic-reading",
  "certificate-ecg-interpretation-vs-echocardiography": "blog/certificate-ecg-interpretation-vs-echocardiography",
  "fellowship-molecular-pathology-vs-cytopathology": "blog/fellowship-molecular-pathology-vs-cytopathology",
  "digital-pathology-ai-diagnostics-india": "blog/digital-pathology-ai-diagnostics-india",
  "point-of-care-ultrasound-pocus-clinical-decisions": "blog/point-of-care-ultrasound-pocus-clinical-decisions",
  "pg-diploma-ultrasonography-vs-certificate-advanced-ultrasound": "blog/pg-diploma-ultrasonography-vs-certificate-advanced-ultrasound",
  "diagnostic-vs-therapeutic-endoscopy": "blog/diagnostic-vs-therapeutic-endoscopy",
  "fellowship-in-gi-endoscopy-eligibility-curriculum-scope": "blog/fellowship-in-gi-endoscopy-eligibility-curriculum-scope",
  "high-salary-medical-career-without-neet": "blog/high-salary-medical-career-without-neet",
  "top-medical-pg-branches-in-india": "blog/top-medical-pg-branches-in-india",
  "most-in-demand-medical-courses-after-mbbs": "blog/most-in-demand-medical-courses-after-mbbs",
  "highest-paying-medical-courses-after-mbbs": "blog/highest-paying-medical-courses-after-mbbs",
  "best-pg-diploma-courses-after-mbbs": "blog/best-pg-diploma-courses-after-mbbs",
  "online-fellowship-courses-after-mbbs": "blog/online-fellowship-courses-after-mbbs",
  "higher-studies-after-mbbs": "blog/higher-studies-after-mbbs",
  "best-medical-courses-after-mbbs-2026": "blog/best-medical-courses-after-mbbs-2026",
  "higher-studies-after-mbbs-2": "blog/higher-studies-after-mbbs-2",
  "pg-diploma-in-ultrasonography-after-mbbs-guide": "blog/pg-diploma-in-ultrasonography-after-mbbs-guide",
  "private-doctor-salary-in-india": "blog/private-doctor-salary-in-india",
  "cardiology-courses-after-mbbs-india-types-duration": "blog/cardiology-courses-after-mbbs-india-types-duration",
  "fellowship-in-cardiology-in-india": "blog/fellowship-in-cardiology-in-india",
  "government-doctor-salary-in-india": "blog/government-doctor-salary-in-india",
  "mbbs-doctor-salary-in-india": "blog/mbbs-doctor-salary-in-india",
  "medical-officer-jobs-after-mbbs": "blog/medical-officer-jobs-after-mbbs",
  "non-clinical-jobs-after-mbbs": "blog/non-clinical-jobs-after-mbbs",
  "clinical-career-after-mbbs": "blog/clinical-career-after-mbbs",
  "government-jobs-after-mbbs": "blog/government-jobs-after-mbbs",
  "doctor-salary-india": "blog/doctor-salary-india",
  "best-jobs-after-mbbs": "blog/best-jobs-after-mbbs",
  "most-in-demand-medical-specialties": "blog/most-in-demand-medical-specialties",
  "highest-paying-medical-specializations": "blog/highest-paying-medical-specializations",
  "how-to-choose-medical-specialization": "blog/how-to-choose-medical-specialization",
  "which-medical-specialization-is-best-after-mbbs": "blog/which-medical-specialization-is-best-after-mbbs",
  "best-specialization-after-mbbs": "blog/best-specialization-after-mbbs",
  "best-gynecology-courses-after-mbbs": "blog/best-gynecology-courses-after-mbbs",
  "courses-after-mbbs-without-neet-pg": "blog/courses-after-mbbs-without-neet-pg",
  "how-to-become-a-cardiologist-india": "blog/how-to-become-a-cardiologist-india",
  "cardiology-courses-after-mbbs": "blog/cardiology-courses-after-mbbs",
  "post-mbbs-fellowship-vs-pg-diploma": "blog/post-mbbs-fellowship-vs-pg-diploma",
  "jobs-after-mbbs": "blog/jobs-after-mbbs",
  "career-after-mbbs": "blog/career-after-mbbs",
  "fellowship-courses-after-mbbs-in-india": "blog/fellowship-courses-after-mbbs-in-india",
  "courses-after-mbbs-in-india": "blog/courses-after-mbbs-in-india",
  // ⚠️ SKIPPED: "fellowship-in-robotic-gynaecological-oncology" — ye slug tumhare
  // LIVE COURSE PAGE ka hai (fellowship-in-gynaecologic-oncology redirect ka target).
  // Isse blog redirect banane se course page hamesha blog pe chala jayega — confirm karo
  // ye sach me blog URL hai ya list me galti se aa gaya.
  "what-to-do-after-mbbs": "blog/what-to-do-after-mbbs",
  "fellowship-in-dermatology-skills": "blog/fellowship-in-dermatology-skills",
  "key-benefits-of-fellowship-in-oncology-for-doctors": "blog/key-benefits-of-fellowship-in-oncology-for-doctors",
  "online-medical-courses-in-india": "blog/online-medical-courses-in-india",
  "online-medical-course-with-certificate": "blog/online-medical-course-with-certificate",
  "online-medical-course-options": "blog/online-medical-course-options",
  "what-are-the-top-requirements-for-a-fellowship-in-paediatric-medicine": "blog/what-are-the-top-requirements-for-a-fellowship-in-paediatric-medicine",
  "how-is-ai-changing-the-curriculum-of-a-dermatology-fellowship": "blog/how-is-ai-changing-the-curriculum-of-a-dermatology-fellowship",
  "best-career-paths-after-a-fellowship-in-emergency-medicine": "blog/best-career-paths-after-a-fellowship-in-emergency-medicine",
  "how-general-laparoscopic-surgery-change-the-patient-experience": "blog/how-general-laparoscopic-surgery-change-the-patient-experience",
  "best-dermatology-courses-for-medical-students-in-2026": "blog/best-dermatology-courses-for-medical-students-in-2026",
  "fellowship-in-pediatric-dermatology-help-you-start-your-own-clinic": "blog/fellowship-in-pediatric-dermatology-help-you-start-your-own-clinic",
  "pg-diploma-in-dermatology-after-mbbs": "blog/pg-diploma-in-dermatology-after-mbbs",
  "career-options-after-a-fellowship-in-reproductive-medicine": "blog/career-options-after-a-fellowship-in-reproductive-medicine",
  "echocardiography-worth-it-for-career-advancement": "blog/echocardiography-worth-it-for-career-advancement",
  "scope-of-ultrasonography-in-2026": "blog/scope-of-ultrasonography-in-2026",
  "fellowship-in-laparoscopy-skills-every-surgeon-should-master": "blog/fellowship-in-laparoscopy-skills-every-surgeon-should-master",
  "career-scope-after-fellowship-in-oncopathology-in-2026": "blog/career-scope-after-fellowship-in-oncopathology-in-2026",
  "fellowship-in-dermatology-a-career-guide": "blog/fellowship-in-dermatology-a-career-guide",
  "fellowship-in-critical-care-complete-guide-for-medical-graduates": "blog/fellowship-in-critical-care-complete-guide-for-medical-graduates",
  "best-city-for-doing-fellowship-in-clinical-genetics": "blog/best-city-for-doing-fellowship-in-clinical-genetics",
  "top-benefits-of-doing-a-fellowship-in-cosmetic-gynecology": "blog/top-benefits-of-doing-a-fellowship-in-cosmetic-gynecology",
  "pg-diploma-in-general-medicine-india": "blog/pg-diploma-in-general-medicine-india",
  "facial-aesthetic-cosmetology-in-2026": "blog/facial-aesthetic-cosmetology-in-2026",
  "interventional-radiology-in-india": "blog/interventional-radiology-in-india",
  "diabetology-after-mbbs-eligibility": "blog/diabetology-after-mbbs-eligibility",
  "diploma-in-dermatology-after-mbbs": "blog/diploma-in-dermatology-after-mbbs",
  "interventional-radiology-after-md-radiology": "blog/interventional-radiology-after-md-radiology",
  "artificial-intelligence-reproductive-medicine-2026": "blog/artificial-intelligence-reproductive-medicine-2026",
  "medical-fellowship-courses-booming-in-india-2026": "blog/medical-fellowship-courses-booming-in-india-2026",
  "medical-career-in-pathology-skills-you-need-to-succeed": "blog/medical-career-in-pathology-skills-you-need-to-succeed",
  "surgical-oncology-education-training-and-career-path": "blog/surgical-oncology-education-training-and-career-path",
  "dermatology-course-career-scope-salary-and-opportunities": "blog/dermatology-course-career-scope-salary-and-opportunities",
  "how-fellowship-in-laparoscopy-hysteroscopy-can-boost-your-medical-career": "blog/how-fellowship-in-laparoscopy-hysteroscopy-can-boost-your-medical-career",
  "certificate-in-family-medicine-complete-guide-2026": "blog/certificate-in-family-medicine-complete-guide-2026",
  "salary-comparison-in-india-and-usa-after-md": "blog/salary-comparison-in-india-and-usa-after-md",
  "why-you-should-consider-a-fellowship-in-fetal-medicine": "blog/why-you-should-consider-a-fellowship-in-fetal-medicine",
  "fellowship-in-internal-medicine-guide-for-mbbs-graduates": "blog/fellowship-in-internal-medicine-guide-for-mbbs-graduates",
  "fellowship-in-dermatology-scope-for-international-practice": "blog/fellowship-in-dermatology-scope-for-international-practice",
  "highest-paying-doctors-in-india": "blog/highest-paying-doctors-in-india",
  "fellowship-in-pediatric-opportunities-in-government-private-sector": "blog/fellowship-in-pediatric-opportunities-in-government-private-sector",
  "the-importance-of-fellowship-in-interventional-cardiology": "blog/the-importance-of-fellowship-in-interventional-cardiology",
};

// 🎭 CONTENT ALIAS: URL apni jagah rahegi (address bar change nahi hoga),
// sirf backend se CONTENT doosre (target) slug ka fetch hoga.
export const ALIASES = {
  "pg-diploma-in-clinical-embryology": "fellowship-in-embryology",
};

export function getRedirectSlug(slug) {
  return REDIRECTS[slug] || null;
}

export function getAliasSlug(slug) {
  return ALIASES[slug] || null;
}

export default REDIRECTS;